services:
  db:
    image: docker.io/library/postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./.pg_storage:/var/lib/postgresql:Z

  caddy:
    image: docker.io/library/caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    cap_add:
      - NET_BIND_SERVICE
      
volumes:
  pg_storage:
  caddy_data:
  caddy_config:
  