services:
  db:
    image: docker.io/library/postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./.pg_storage:/var/lib/postgresql:Z

volumes:
  pg_storage: